theme: jekyll-theme-modernist

plugins:
#  - jekyll-feed
#  - jekyll-redirect-from
#  - jekyll-avatar
#  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache
#  - jekyll-seo-tag
  - jekyll-sitemap

# lang: en-US (default)

repository: betaiotazeta/AutoShiftPlanner

url: "https://betaiotazeta.github.io/AutoShiftPlanner"

title: Auto Shift Planner

description: Auto Shift Planner is a free user-friendly desktop application that can design detailed employees shift schedules and solve them automatically while meeting the maximum satisfaction of constraints.

show_downloads: true

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-117502664-1

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: autoshiftplanner

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
#  - LICENSE
#  - README.md
#  - CNAME
